version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: fitness-rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - fitness-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: fitness-keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
    ports:
      - "8181:8080"  # Map host port 8181 to container port 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - fitness-network
    depends_on:
      - rabbitmq

networks:
  fitness-network:
    driver: bridge

volumes:
  rabbitmq_data:
