version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: fitness-rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - fitness-network

networks:
  fitness-network:
    driver: bridge

volumes:
  rabbitmq_data:
