spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs



  cloud:
    gateway:
      routes:
        -  id : user-service
           uri : lb://USER-SERVICE
           predicates:
             - Path=/api/users/**
        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activities/**
        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/recommendations/**
server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: false
    hostname: localhost
    appname: ${spring.application.name}
    status-page-url: http://localhost:${server.port}/actuator/info
    health-check-url: http://localhost:${server.port}/actuator/health
    home-page-url: http://localhost:${server.port}/