spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_db
    username: fitness_user
    password: fitness_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Server port configuration (optional)
server:
  port: 8080

# Logging configuration (optional)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
